[package]
name = "openapi-gen"
version = "0.1.0"
edition = "2021"
default-run = "openapi-gen"

[dependencies]
anyhow = { version = "1.0.71" }
async-trait = "0.1.68"
base64 = { version = "0.21.0", optional = true }
bounded-integer = { version = "0.5.6", features = ["std", "types", "serde1", "num-traits02"], optional = true }
clap = { version = "4.2.7", features = ["derive"], optional = true }
derive_more = "0.99.17"
heck = "0.4.1"
http = "0.2.9"
http-api-problem = { version = "0.57.0", optional = true }
indexmap = "1.9.3"
openapiv3 = { version = "2.2.1", package = "openapiv3-extended" }
prettyplease = "0.2.4"
proc-macro2 = "1.0.56"
quote = "1.0.27"
regress = { version = "0.6.0", optional = true }
reqwest = { version = "0.11.18", features = ["blocking"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_with = { version = "3.0.0", optional = true }
serde_yaml = { version = "0.9.21", optional = true }
syn = "2.0.15"
thiserror = "1.0.40"
time = { version = "0.3.21", features = ["formatting", "parsing", "macros", "serde"] }
uuid = { version = "1.3.2", optional = true }

[dev-dependencies]
atty = "0.2.14"
serde_yaml = { version = "0.9.21", optional = false }
similar = "2.2.1"
syn = { version = "2.0.15", features = ["extra-traits"] }
termcolor = "1.2.0"

[features]
default = []
api-problem = ["http-api-problem"]
cli = ["clap", "serde_yaml"]
bytes = ["base64", "serde_with"]
integer-restrictions = ["bounded-integer"]
scripts = ["cli"]
string-pattern = ["regress"]

[[bin]]
name = "openapi-gen"
required-features = ["cli"]
