[package]
name = "openapi-gen"
version = "0.1.0"
edition = "2021"
default-run = "openapi-gen"

[dependencies]
anyhow = { version = "1.0.71", optional = true }
async-trait = "0.1.68"
base64 = { version = "0.21.0", optional = true }
bounded-integer = { version = "0.5.6", features = ["std", "types", "serde1", "num-traits02"], optional = true }
clap = { version = "4.2.7", features = ["derive"], optional = true }
derive_more = "0.99.17"
heck = "0.4.1"
http = "0.2.9"
http-api-problem = "0.56.0"
indexmap = "1.9.3"
openapiv3 = { version = "2.2.1", package = "openapiv3-extended" }
prettyplease = "0.2.4"
proc-macro2 = "1.0.56"
quote = "1.0.27"
regress = { version = "0.6.0", optional = true }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = { version = "0.9.21", optional = true }
syn = "2.0.15"
thiserror = "1.0.40"
time = { version = "0.3.21", features = ["formatting", "parsing", "macros"] }
uuid = { version = "1.3.2", optional = true }

[features]
default = []
cli = ["anyhow", "clap", "serde_yaml"]
bytes = ["base64"]
integer-restrictions = ["bounded-integer"]
scripts = ["cli"]
string-pattern = ["regress"]

[[bin]]
name = "openapi-gen"
required-features = ["cli"]

[[bin]]
name = "parse"
required-features = ["scripts"]

[[bin]]
name = "operations"
required-features = ["scripts"]
